#!/bin/bash

url='localhost:5000'

curl "$url/addUser/asp781/Alex_Palmatier"
curl "$url/addUser/ams6652/Aaron_Segal"
curl "$url/addUser/bcf283/Brendan_Flood"
curl "$url/addUser/ctn494/Cam_Nguyen"
curl "$url/addUser/cjc3635/Craig_Carr"
curl "$url/addUser/drs3326/Daniel_Schoepflin"
curl "$url/addUser/djs4287/Daniel_Speichert"
curl "$url/addUser/dtm528/Dario_Marasco"
curl "$url/addUser/leblanc9/Emily_LeBlanc"
curl "$url/addUser/gjk381/Greg_Klepic"
curl "$url/addUser/grd362/Gregory_Dorchies"
curl "$url/addUser/timoping3/Haoyue_Ping"
curl "$url/addUser/jae634/Jenn_Engimann"
curl "$url/addUser/jg32655/Jeromy_Guinther"
curl "$url/addUser/stokesj846/Jonathan_Stokes"
curl "$url/addUser/wongzeonbong7/Junbang_Huang"
curl "$url/addUser/kmc4658/Karishma_Changlani"
curl "$url/addUser/mwa299/Mark_Albrecht"
curl "$url/addUser/mm38881/Max_Mattes"
curl "$url/addUser/mkl2/Meaghan_Lutts"
curl "$url/addUser/na5283/Ni_An"
curl "$url/addUser/psw364/Paras_Wadekar"
curl "$url/addUser/rna455/Rod_Aluise"
curl "$url/addUser/rmc3476/Ryan_Corcoran"
curl "$url/addUser/sc33747/Sean_Campbell"
curl "$url/addUser/spg638/Sean_Grimes"
curl "$url/addUser/wx289/Wenyu_Xin"
curl "$url/addUser/zeb231/Zachary_Bryceland"
curl "$url/closeRegistration/"
